# Generated by Django 5.2.4 on 2025-07-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_address', models.CharField(blank=True, default='', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_hours', models.CharField(blank=True, default='', max_length=100)),
                ('footer_research_domains', models.JSONField(blank=True, default=list)),
                ('footer_team_introduction', models.TextField(blank=True, default='')),
                ('footer_team_name', models.CharField(blank=True, default='', max_length=255)),
                ('footer_copyright', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
