# Generated by Django 5.2.4 on 2025-08-21 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboissim', '0008_rename_results_impact_project_impact_project_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='impact',
        ),
    ]
