# Generated by Django 5.2.4 on 2025-08-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboissim', '0009_remove_project_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
